services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: "1000:1000"
    ports:
      - "8096:8096"
    volumes:
      - /home/chengwei1/docker/jellyfin/config:/config
      - /home/chengwei1/docker/jellyfin/cache:/cache
      - /mnt/Movies:/media
      - /mnt/photo-folder:/media/photos
    restart: unless-stopped